name: repocheck
description: Control de reposición tercerizada
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - Updated to official versions
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  flutter_riverpod: ^2.4.9
  
  # Camera & Location
  camera: ^0.10.5+5
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  image_picker: ^1.0.4
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
